apiVersion: v1
kind: Service
metadata:
  name: privacyvault-monolith
  labels:
    app: privacyvault-ai
spec:
  selector:
    app: privacyvault-ai
    component: monolith
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
